type Field {
  testField: String!
}

type Post {
	imageUrl: String!
	productUrl: String!
	user: User
}

type User {
	username: String! @unique
	email: String! @unique
	posts: [Post] @relation
	confirmed: Boolean
	website: String
}

type Query {
  entries: [Field]
	users: [User]
	user(username: String!): User
	userByEmail(email: String!): User
	posts: [Post]
}

# type Mutation {
#   createPost(input: PostInput): Post
#   updatePost(id: ID!, input: PostInput): Post
# }
